Initialize _objectAlignmentInBytes
error: expected primary-expression before
‘objectAlignmentInBytes’.

I think the _objectAlignmentInBytes method is defined
in the OMR::ObjectModel class with the
OMR::ObjectModelConnector alias.

Signed-off-by: Amarpreet Singh amarpreet1997@gmail.com